version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    prefix: 'fix'
    include: 'scope'
    prefix-development: 'chore'
  cooldown:
    default-days: 3
